### ISSUE TITLE
Mixed doesn't seem to work for multiple classes

### ISSUE THREAD

**Issue by MickeL** [ayonli/class-mixins#2]
Im using deno 1.14.0

Either I have miss-understood how to use Mixed or there seems to be something wrong :)

intellisense seem to work but the mixed type (C in this case) only gets properties from the first parameter to Mixed.

```typescript
import { Mixed } from 'https://deno.land/x/class_mixins/index.ts';

class A {
  a = 'A';
}

class B {
  b = 'B';
}

class C extends Mixed(A, B) { }

const instance = new C();
console.log(instance.a);
console.log(instance.b);
```

Output
A
undefined

Thanks

**Comment by ayonli** [comment]
Sorry, I didn't see the issue in the past. The problem you highlighted is that mixin does not work precisely like multi-inheritance, when instantiating, only the base class (the first one, in your case, class `A`) will be initiated, for other classes, it just copies their methods from the prototype. And the properties do not come from the prototype, they are initiated when instantiating, and the mixed classes are never instantiated, so the property `b` in your case will never appear on the instance of class `C`. I hope you have sorted that out yourself, again, sorry for not responding in time.
